#!/usr/bin/env python

# batch to generate all the nuts of the same units, including all the
# pitches.
# By Nenad Rijavec.
# Distributed under MIT license.

import argparse
import sys
from fractions import Fraction
from generate import *
from dimensions import *

# Define your custom HelpFormatter
class ColoredHelpFormatter(argparse.RawTextHelpFormatter):
    def _format_args(self, action, default_metavar=None):
        # Set the color for optional parameter values
        #optional_color = '\033[94m'  # Bright blue color
        optional_color = '\033[95m'  # Bright magenta color
        reset_color = '\033[0m'      # Reset color

        if action.nargs == 0:
            return ''

        # Use the default formatting
        metavar = super()._format_args(action, default_metavar)

        # Return the formatted string with color
        return f'{optional_color}{metavar}{reset_color}'

def parse_int(name, value: str) -> int:
	try:
		return int(value)
	except Exception:
		sys.exit(f'{name}: invalid number syntax: "{value}"')

def parse_number(name, value: str, units: str) -> float:
	try:
		if units == 'mm' or not '/' in value :
			return float(value)

		parts = value.strip().split(' ')
		if len(parts) == 1:
			return float(Fraction(parts[0]))
		elif len(parts) == 2:
			return int(parts[0]) + float(Fraction(parts[1]))
		else:
			raise ValueError
	except Exception:
		sys.exit(f'{name}: invalid number syntax: "{value}"')
		#raise argparse.ArgumentTypeError(f'invalid number syntax: '{value}'')


def positive(value: float, name: str):
	if value <= 0:
		sys.exit(f'Error: {name} must be > 0')

def main():
	parser = argparse.ArgumentParser(
		description='Makes all the predefined nuts for the given'+
		' unit (mm or in).',
		formatter_class=ColoredHelpFormatter
	)

	# positional arguments
	parser.add_argument(
		'units',
		choices=['mm', 'in'],
		help='units, mm (metric) or in (imperial)',
	)

	# optional arguments

	parser.add_argument(
		'-v', '--verbose',
		action='store_true',
		help=( "Verbose output" )
	)
	parser.add_argument(
		'--fn',
		dest='fn',
		default='50',
		help=("Number of segments for each cylinder."
		)
	)
	parser.add_argument(
		'--prefix',
		dest='prefix',
		help=("File name prefix."
		)
	)

	args = parser.parse_args()
	fn = parse_int('fn', args.fn)
	positive(fn, "fn")

	if args.units == "mm" :
		am_metric = True
		nuts = metric_nuts
	else :
		am_metric = False
		nuts = imperial_nuts

	# numeric parsing
	for orig in nuts :
		bld = make_build_nut( am_metric, orig.desc.replace('M', '' ))
		
		if bld.diam < 8 :
			diam_adj = 0.40
		elif bld.diam < 9.5 :
			diam_adj = 0.7
		else :
			diam_adj = 0.8
		hex_adj = -0.5
		hex = bld.hex_a
		length = bld.hex_h
		for pitch in bld.pitches :
	
			fname = ""
			fname += f"{args.units}" + "_"
			fname += "nut_"
			fname += bld.desc.replace("/","f").replace(" converted","")
			fname += "X"
			if am_metric :
				fname += str("{:.2f}".format(pitch))
			else :
				fname += str("{:.0f}".format(25.4/pitch))
			if am_metric :
				ll = bld.hex_h
			else :
				ll = bld.hex_h / 25.4  # bld is in metric
			fname += '-def'+str("{:.2f}".format(ll))
			fname = fname.replace(".","p")
			fname += ".stl"
		
			print( fname )
		
			facets = []
		
			generate_nut( am_metric, bld, pitch, length, hex, fn,
					diam_adj, hex_adj, facets)
			comment = fname + ' generated by nutgen'
			comment += ' diam_adj=' + str("{:.2f}".format(diam_adj))
			comment += ' hex_adj=' + str("{:.2f}".format(hex_adj))
			if not args.prefix == None :
				fname = args.prefix + fname
			
			write_binary_stl( fname, comment, facets )

if __name__ == "__main__":
	main()

