# generated by ChatGPT 5 on chatgpt.com 
# see bottom of the file for the hints used
# Hints by Nenad Rijavec.
# Distributed under MIT license.

# NOTE : requires at least three objects.

# This module packs a set of given cylindrical objects to minimize the
# area. We don't really care about the area covered. We care that the
# adjacent objects are as close as possible to each othe (MIN_GAP). This
# way, when printed, the printer spends minimal time traversing between
# the objects.

# Packing to a minimal area is a hard problem, but this module produces a
# good suboptimal solution which provides a path through the objects with all
# the gaps being MIN_GAP or similar.

import numpy as np
from scipy.optimize import minimize
from itertools import combinations

MIN_GAP = 0.25


def arrange_circles(radii, max_iter=5000, seed=0):
    """
    Arrange circles in the plane with constraints:
    - minimum gap between circles
    - no containment
    - at least two neighbors at minimum distance
    - compact packing

    Parameters
    ----------
    radii : list[float]
        Radii of the circles
    max_iter : int
        Optimization iterations
    seed : int
        Random seed

    Returns
    -------
    centers : list[tuple[float, float]]
        (x, y) coordinates of circle centers
    """

    np.random.seed(seed)
    radii = np.asarray(radii)
    N = len(radii)

    # Initial guess: random compact cluster
    x0 = np.random.randn(2 * N) * np.mean(radii)

    def energy(x):
        pts = x.reshape(N, 2)
        E = 0.0

        # Pairwise penalties
        for i, j in combinations(range(N), 2):
            d = np.linalg.norm(pts[i] - pts[j])
            target = radii[i] + radii[j] + MIN_GAP

            # Overlap / gap penalty
            if d < target:
                E += 1000.0 * (target - d) ** 2

            # Containment penalty
            if d + min(radii[i], radii[j]) < max(radii[i], radii[j]):
                E += 2000.0

        # Neighbor count encouragement
        for i in range(N):
            distances = []
            for j in range(N):
                if i == j:
                    continue
                d = np.linalg.norm(pts[i] - pts[j])
                target = radii[i] + radii[j] + MIN_GAP
                distances.append(abs(d - target))

            distances.sort()
            # Encourage two close neighbors
            E += 50.0 * (distances[0] ** 2 + distances[1] ** 2)

        # Compactness: minimize bounding box area
        min_x, min_y = pts.min(axis=0)
        max_x, max_y = pts.max(axis=0)
        area = (max_x - min_x) * (max_y - min_y)
        E += 0.1 * area

        return E

    result = minimize(
        energy,
        x0,
        method="L-BFGS-B",
        options={"maxiter": max_iter}
    )

    centers = result.x.reshape(N, 2)
    return [tuple(p) for p in centers]

""" # begin hints
I have a python list of N floating point numbers. N is small, probably less
than 20. Each number in the list is a radius of a circle. Write a module
that arranges these circles in the plane with following conditions:
- circles have to be at least 0.25 of unit used in radii from one another
- no circle can contain another circle
- every circle should have at least two neighboring circles 0.25 units
  distant
- circles should be packed in as small area as possible.

The module should return a list of N 2-tuples, each containing the
coordinates of the corresponding circle in the original list.

Any publicly available python package can be used.
""" # end hints
