#!/usr/bin/env python3

# Takes a list of stl files and combines them into a single stl file. The
# objects are packed to minimize the moves during printing.
# Packing module by ChatGPT 5 computes the position of each object.

# Comments from each input file are discarded. Two output files are made:
# the specified output file containing the merged objects and the list
# file of the same name with .list appended, containing the list of files
# that were merged.

# We make the list file, since the 80 byte comment in the output stl file
# doesn't have the space to list all the input filenames.
# By Nenad Rijavec.
# Distributed under MIT license.

import sys
import math
import struct

from facets import *
from dimensions import *
from constructs import *
from parts import *
from pack import *

nargs = len(sys.argv)
if nargs < 4 :
	print( 'Needs at least two input files and an output file' )
	print( 'usage: '+sys.argv[0]+ ' <2 or more STL files> <output file>' )
	sys.exit(1)

print( nargs-2, ' files to merge' )

listname = sys.argv[nargs-1] + '.list'
listfile = open( listname, 'w' )
facetarray = []
commentarray = []
radii = []
for n in range(1,nargs-1) :
	print( 'reading ' + sys.argv[n] )
	listfile.write( sys.argv[n] + '\n' )
	[comment, facets ] = read_binary_stl( sys.argv[n] )
	print( len(facets), ' facets' )
	commentarray.append( [ comment ] )
	facetarray.append( [ facets ] )
	r = 0
	for facet in facets :
		if r < facet.vt0.r :
			r = facet.vt0.r
		if r < facet.vt1.r :
			r = facet.vt1.r
		if r < facet.vt2.r :
			r = facet.vt2.r
	radii.append( r )
listfile.close()
radstr = ''
#for r in radii:
#	radstr += str("{:.4f}".format(r)) + ' '
#print( 'radii : ' + radstr)

if len(radii) == 2 :
	# we do this simple case by hand, arrange_circles needs at least 3
	d = radii[0] + radii[1] + 0.1
	positions = [ [-d/2, 0], [d/2, 0] ]
else :
	# in pack.py, generated by ChatGPT 5
	positions = arrange_circles( radii )

outfacets = []
for n in range(0,len(facetarray)) :
	facets = (facetarray[n])[0]
	dx = (positions[n])[0]
	dy = (positions[n])[1]
	for facet in facets :
		facet.vt0.x += dx
		facet.vt1.x += dx
		facet.vt2.x += dx
		facet.vt0.y += dy
		facet.vt1.y += dy
		facet.vt2.y += dy
		outfacets.append( facet )
print( len(outfacets), 'output facets' )

write_binary_stl( sys.argv[nargs-1], \
	'stlpack output :'+str(len(facetarray))+' files combined', outfacets)
